services:
  - type: web
    name: tienda-poo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -w 1 -b 0.0.0.0:$PORT
    envVars:
      - key: ADMIN_PASS
        value: admin1234
